language: perl

before_install:
 - sudo apt-get install -qq libkeybinder-dev libkeybinder0
 - cpanm -v --notest ExtUtils::Depends ExtUtils::PkgConfig

install: cpanm -v --installdeps --notest .

perl:
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
