---
abstract: 'Perl extension that wraps libkeybinder for GTK apps'
author:
  - 'Ivan Baidakou <dmol@(none)>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.8, CPAN::Meta::Converter version 2.131560'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Keybinder
no_index:
  directory:
    - t
    - inc
requires:
  Gtk2: 1.247
version: 0.02
