---
abstract: 'Perl extension that wraps libkeybinder for GTK apps'
author:
  - 'Ivan Baidakou <dmol@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.84, CPAN::Meta::Converter version 2.133380'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Keybinder
no_index:
  directory:
    - t
    - inc
    - t
requires:
  Gtk2: 1.247
  perl: 5.010001
resources:
  bugtracker: http://github.com/basiliscos/p5-Keybinder/issues
  homepage: http://github.com/basiliscos/p5-Keybinder
  license: http://www.opensource.org/licenses/artistic-license-2.0
  repository: http://github.com/basiliscos/p5-Keybinder
version: 0.03
